// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkPtysjodxh356vyuQSaAhg59xjeHjMVU',
    appId: '1:346631879936:web:ddb922f803629a1cec47e5',
    messagingSenderId: '346631879936',
    projectId: 'smart-drying-iot',
    authDomain: 'smart-drying-iot.firebaseapp.com',
    storageBucket: 'smart-drying-iot.firebasestorage.app',
    measurementId: 'G-9B1ZDGC4JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF6qh928QqLNNHXKZ2My1kP7FtefxggmY',
    appId: '1:346631879936:android:de955d5384477ae0ec47e5',
    messagingSenderId: '346631879936',
    projectId: 'smart-drying-iot',
    storageBucket: 'smart-drying-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4gfV9-frj8zDygDJ3GJ1oM08QCyiaZQ0',
    appId: '1:346631879936:ios:bb8f5ca55acaf79fec47e5',
    messagingSenderId: '346631879936',
    projectId: 'smart-drying-iot',
    storageBucket: 'smart-drying-iot.firebasestorage.app',
    iosBundleId: 'com.example.flutterFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4gfV9-frj8zDygDJ3GJ1oM08QCyiaZQ0',
    appId: '1:346631879936:ios:bb8f5ca55acaf79fec47e5',
    messagingSenderId: '346631879936',
    projectId: 'smart-drying-iot',
    storageBucket: 'smart-drying-iot.firebasestorage.app',
    iosBundleId: 'com.example.flutterFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkPtysjodxh356vyuQSaAhg59xjeHjMVU',
    appId: '1:346631879936:web:7c654290411f1e0aec47e5',
    messagingSenderId: '346631879936',
    projectId: 'smart-drying-iot',
    authDomain: 'smart-drying-iot.firebaseapp.com',
    storageBucket: 'smart-drying-iot.firebasestorage.app',
    measurementId: 'G-J9HJ1LVYHD',
  );
}
